server:
  port: 8080
  servlet:
    context-path: /ticketAdmin

spring:
  datasource:
    url: jdbc:mysql://111111:3306/ticket?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=false
    username: kangmeng
    password: Kangmeng*123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_identifier_rollback: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        hikari:
          dataSource:
            cachePrepStmts:true
            prepStmtCacheSize:250
            prepStmtCacheSqlLimit:2048
            useServerPrepStmts:true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:  com.km086.admin.config.TableNamingStrategy
  mail:
    host: smtp.163.com
    username: chenhao21@163.com
    password: hugh790321
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  devtools:
    restart:
      enabled: true

wx:
  pay:
    appId: wx2036f82df69e9721
    mchId: 1245325402
    mchKey: 1234qwer1234asdf1234zxcv1234qwer
    keyPath: d:/git/wx/apiclient_cert.p12
    billIp: 120.76.238.115

wechat:
  certificate_location: /root/apiclient_cert.p12
  spbill_create_ip: 120.76.238.115
  app_id: wx2036f82df69e9721
  secret: 593c5b283e84d43d16feafcc1813ad68
  token: csyAh8MuCS2D9t5CE5tA
  aes_key: NxNOSOHzcjQEbdRO1smbbChtPVQEELTW5foj62UptTS
  partner_id: 1245325402
  partner_key: 1234qwer1234asdf1234zxcv1234qwer
  enterprise_pay_url: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers

#schedule
bill:
  cron: 0 30 10 * * *
  agentCron: 0 0 10 ? * MON
  delayDay: 2

ticketMail:
  to: 15993233@qq.com,1377008716@qq.com

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  needPayProcessNum: 10
  noNeedPayProcessNum: 2
  imageDir: /home/images
  apkDir: /home/apk
  superPassword: kangmeng2017@

logging:
  level:
    org.springframework:
      data: INFO
      security: DEBUG